travis:
  secure:
    BINSTAR_TOKEN: Kt00BtyEOpCNo9VYBjheESWXADjPYjwxIxuz5RupGERgGR0A0n4kXZHFZ7uKTpcqMfHFZ+XskJnMKNZzSECzP/WHrL6VhHets15RCfFRV991t8qumZudn3ghbNAykJfuWlGpRyex5EFYx27uZyAW/Y1g8H1wNl103uOiwZ/ufDfEMDyPMxFS2QhU/2bs6Lf+Xy5rsdVgK24wZvWWWgJDuzBKOA6qawDz7v29Qn4J4SPQJ4s5TWI16LcCvpEt0QdiSiHeKrUY1wvtnOkLfbilQPhLtpwv3e9LTwjuSocfSk9TAP1q74FdJu4AZIAm30+FTMvull7snyOkVr5MkXFJP2U77gajiGn/v6eunG5x2MYk3J9yUfHL/ecVlV0H0c/dA6FwmASCIGLig7FpENGDOoW2JKI26aWISE98w2wMb5BXYHC/n042+FSChWW1XsDkUP0OFyp2eCVV1mwUEWi4rVd13Da/fOVydCYTDB47T3h92SM5Hxoqqd5PTF6Ux8lgY0kLKrlgN2gf46B8byFs9aB+CSMAIn5cS/5OviqOokDw4t4sy53CLlNTTMPotuBofG6TYenxQjXwY7SuME4o6uxTljo7nII6zWk5QE2x9Ztjdh+sYqpdC0x3Wk0LEHvFq0eKTxP1cjJPJUTDPmTvc2pjesIB9fthVgmZP7omVz0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
